menus/urls.py
from django.conf.urls import url


from .views import (
    ItemCreateView,
    ItemDetailView,
    ItemListView,
    ItemUpdateView,
)
urlpatterns = [
    url(r'^create/$',  ItemCreateView.as_view(), name='create'),
    #url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(), name='edit'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'),
    url(r'$', ItemListView.as_view(), name='list'),
]

pipicky/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from restaurants.views import TemplateView
from restaurants.views import (
    # restaurant_listview,
    RestaurantListView,
    RestaurantDetailView,
    restaurant_createview,
    # RestaurantCreateView
)
from django.contrib.auth.views import LoginView, LogoutView
from profiles.views import ProfileFollowToggle, RegisterView, \
    activate_user_view
from menus.views import HomeView

"""class based view related to line 53 in views.py"""
# from restaurants.views import HomeView, AboutView, ContactView
#
# """instead of above line you can import TemplateView, use TemplateView
# instead of any page view in path and just write Template_name= page.html,
# inside parenthesis in as_view() """
#
# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('', TemplateView.as_view(template_name='home.html')),
#     path('about/', TemplateView.as_view(template_name='about.html')),
#     path('contact/', TemplateView.as_view(template_name='contact.html')),
# ]


"""build new view using models.py"""

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', HomeView.as_view(), name='home'),
    re_path(r'^login/$', LoginView.as_view(), name='login'),
    re_path(r'^logout/$', LogoutView.as_view(), name='logout'),
    re_path(r'^register/$', RegisterView.as_view(), name='register'),
    re_path(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),
    re_path(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow'),
    re_path(r'^restaurants/', include(('restaurants.urls', 'restaurants'), namespace='restaurants')),
    re_path(r'^items/', include(('menus.urls', 'menus'), namespace='menus')),
    re_path(r'^u/', include(('profiles.urls', 'profiles'), namespace='profiles')),
    # re_path(r'^restaurants/$', RestaurantListView.as_view(), name='restaurants'),
    # re_path(r'^restaurants/create/$', RestaurantCreateView.as_view(), name='restaurant_create'),
    # re_path(r'^restaurants/create/$', restaurant_createview),
    # re_path(r'^restaurants/(?P<slug>\w+)/$', RestaurantListView.as_view()),
    # re_path(r'^restaurants/(?P<slug>[\w-]+)/$', RestaurantDetailView.as_view(), name='restaurant_detail'),
    re_path(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    re_path(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
]

profiles/urls.py
from django.conf.urls import url

from .views import ProfileDetailView, RandomProfileDetailView

urlpatterns = [
    url(r'^random/$', RandomProfileDetailView.as_view(), name='random'),
    url(r'^(?P<username>[\w-]+)/$', ProfileDetailView.as_view(), name='detail'),
]

templates/snippets/css.html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
      integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

templates/snippets/form_snippet.html
{% if errors %}
{{ form.errors }}
{% endif %}

<form method="POST"> {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>

templates/snippets/js.html
<script scr="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>

templates/snippets/nav.html
<div class='container'>
    <div class='row text-center'>
        <div clsas='col-sm-6 col-sm-offset-3'>
            <h1>MuyPicky.com</h1>
            <a href='{% url "home" %}'>Home</a>
            <!-- <a href='{% url "about" %}'>About</a>
            <a href='{% url "contact" %}'>Contact</a> -->
            <a href='{% url "profiles:random" %}'>Random User</a>
            {% if request.user.is_authenticated %}
            <a href='{% url "restaurants:list" %}'>Restaurants</a>
            <a href='{% url "menus:list" %}'>Menu Items</a>
            <a href='{% url "logout" %}'>Logout</a>
            {% else %}
            <a href='{% url "register" %}'>Register</a>
            <a href='{% url "login" %}'>Login</a>

            {% endif %}
        </div>
    </div>

</div>
<hr/>

templates/snippets/sidebar.html
<ul>
    <li>Item 1</li>
    <li>Item 2</li>
    <li>Item 3</li>
</ul>